apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins-master
  ports:
    - name: http-port
      port: 8080
      targetPort: 8080
      nodePort: 30000
